### ISSUE TITLE
A problem about training data

### ISSUE THREAD

**Issue by ljx761795750** [junshengzhou/3DAttriFlow#10]
Hi, thank you for your work. I have a data and question about the training period,i have done unzip ShapeNetV1PointCloud.zip and unzip ShapeNetV1Renderings.zip 。Is there a problem with my dataset？
Traceback (most recent call last):
  File "val_svr.py", line 83, in <module>
    val()
  File "val_svr.py", line 23, in val
    dataloader_test = build_dataset_val(args)
  File "/****/*****/****/3DAttriFlow-main/dataset_svr/trainer_dataset.py", line 32, in build_dataset_val
    dataset_test = dataset_shapenet.ShapeNet_val(args, train=False)
  File "/***/*****/****/3DAttriFlow-main/dataset_svr/dataset_shapenet.py", line 298, in __init__
    new_classes.append(self.names2id[category])
KeyError: 'airplane'

**Comment by junshengzhou** [comment]
Hi,
Thanks for your interest. I think the problem is caused by the lack of `taxonomy` file, which is used to set up `self.names2id`. Please make sure that you put the `taxonomy` file in the right place.
